### ISSUE TITLE
List of clubs

### ISSUE THREAD

**Issue by dvtdyn** [dvtdyn/capstone-project#1]
## Value statement
As a **football player** 
I need **a list of registered football clubs** 

## Description
![Uploading IMG_20191124_223238.jpg…]()
## Acceptance criteria
- [ ] Scrolling list of Clubs with logo, name and website link

## Tasks
- [ ] .json file with 20 Football Clubs from Hamburg, logo, name, website link
- [ ] Create Club component in storybook, incl. Sketchdesign 
- [ ] Add Club component to App
- [ ] Test on mobile phone

## Size
small
