### ISSUE TITLE
Add interactive buttons to club

### ISSUE THREAD

**Issue by dvtdyn** [dvtdyn/capstone-project#4]
## Value statement
As a **football player** 
I need **interactive buttons** 
so that **I can contact clubs via phone and mail or go to their website** 

## Description
![IMG_20191125_123037](https://user-images.githubusercontent.com/55998660/69540688-8a173600-0f87-11ea-8d85-95e5d8f1e709.jpg)

## Acceptance criteria
- [ ] Call button opens call function on your phone
- [ ] mail button opens your standard mail app
- [ ] website button opens the website of the club

## Tasks
- [ ] update sketch design with the interactive buttons
- [ ] add the information of the interactive buttons to club.json
- [ ] add interactive buttons to Club component in storybook:
    - [ ] phone button opens phone on your mobile device
    - [ ] mail button opens mail app
    - [ ] website button opens the website of the club
- [ ] test new functions on mobile

## Size
medium
