### ISSUE TITLE
Club overview with the teams onClick

### ISSUE THREAD

**Issue by dvtdyn** [dvtdyn/capstone-project#5]
## Value statement
As a **football player** 
I need **an overview about the clubs** 
so that **I can see the teams of the club** 

## Description
![IMG_20191125_123103](https://user-images.githubusercontent.com/55998660/69541303-16762880-0f89-11ea-864b-26a97c529358.jpg)

## Acceptance criteria
- [ ] New Screen with a list of teams

## Tasks
- [ ] build sketch design for new screen
- [ ] create ClubOverview component in storybook
- [ ] check if GlobalStyle is to be updated
- [ ] research for react router
- [ ] implement dynamic url for the club name in url with react router
- [ ] implement new Component in Club/App
- [ ]Test on mobile phone

## Size
large
