### ISSUE TITLE
Filter function to List of Clubs

### ISSUE THREAD

**Issue by dvtdyn** [dvtdyn/capstone-project#6]
## Value statement
As a **football player** 
I need **to be able to see the clubs playing in a specific league** 
so that **there is less visual clutter for the players to find the relevant club** 

## Description
![Filter function to List of Clubs](https://user-images.githubusercontent.com/55998660/69543634-525fbc80-0f8e-11ea-8aed-7d8198595113.jpg)

## Acceptance criteria
- [ ] Filter Clubs by league

## Tasks
- [ ] Create a filter Component in Storybook
- [ ] Add filter component to the list of clubs

## Size
large
